//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.OrmTestsObjects
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// UpdateObjectTestBS.
    /// </summary>
    // *** Start programmer edit section *** (UpdateObjectTestBS CustomAttributes)

    // *** End programmer edit section *** (UpdateObjectTestBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class UpdateObjectTestBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (UpdateObjectTestBS CustomMembers)

        // *** End programmer edit section *** (UpdateObjectTestBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateAggregatorUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateAggregatorUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateAggregatorUpdateObjectTest(NewPlatform.OrmTestsObjects.AggregatorUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateAggregatorUpdateObjectTest)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateAggregatorUpdateObjectTest)
        }
        
        // *** Start programmer edit section *** (OnUpdateMasterUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateMasterUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMasterUpdateObjectTest(NewPlatform.OrmTestsObjects.MasterUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateMasterUpdateObjectTest)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateMasterUpdateObjectTest)
        }
        
        // *** Start programmer edit section *** (OnUpdateDetailUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (OnUpdateDetailUpdateObjectTest CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateDetailUpdateObjectTest(NewPlatform.OrmTestsObjects.DetailUpdateObjectTest UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateDetailUpdateObjectTest)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateDetailUpdateObjectTest)
        }
    }
}
