//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.OrmTestsObjects
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DetailUpdateObjectTest.
    /// </summary>
    // *** Start programmer edit section *** (DetailUpdateObjectTest CustomAttributes)

    // *** End programmer edit section *** (DetailUpdateObjectTest CustomAttributes)
    [BusinessServer("NewPlatform.OrmTestsObjects.UpdateObjectTestBS, OrmTestsObjects.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DetailUpdateObjectTestE", new string[] {
            "DetailName",
            "AggregatorUpdateObjectTest",
            "Master",
            "Master.MasterName",
            "Master.Detail"}, Hidden=new string[] {
            "AggregatorUpdateObjectTest",
            "Master",
            "Master.MasterName",
            "Master.Detail"})]
    public class DetailUpdateObjectTest : ICSSoft.STORMNET.DataObject
    {
        
        private string fDetailName;
        
        private NewPlatform.OrmTestsObjects.MasterUpdateObjectTest fMaster;
        
        private NewPlatform.OrmTestsObjects.AggregatorUpdateObjectTest fAggregatorUpdateObjectTest;
        
        // *** Start programmer edit section *** (DetailUpdateObjectTest CustomMembers)

        // *** End programmer edit section *** (DetailUpdateObjectTest CustomMembers)

        
        /// <summary>
        /// DetailName.
        /// </summary>
        // *** Start programmer edit section *** (DetailUpdateObjectTest.DetailName CustomAttributes)

        // *** End programmer edit section *** (DetailUpdateObjectTest.DetailName CustomAttributes)
        [StrLen(255)]
        public virtual string DetailName
        {
            get
            {
                // *** Start programmer edit section *** (DetailUpdateObjectTest.DetailName Get start)

                // *** End programmer edit section *** (DetailUpdateObjectTest.DetailName Get start)
                string result = this.fDetailName;
                // *** Start programmer edit section *** (DetailUpdateObjectTest.DetailName Get end)

                // *** End programmer edit section *** (DetailUpdateObjectTest.DetailName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailUpdateObjectTest.DetailName Set start)

                // *** End programmer edit section *** (DetailUpdateObjectTest.DetailName Set start)
                this.fDetailName = value;
                // *** Start programmer edit section *** (DetailUpdateObjectTest.DetailName Set end)

                // *** End programmer edit section *** (DetailUpdateObjectTest.DetailName Set end)
            }
        }
        
        /// <summary>
        /// DetailUpdateObjectTest.
        /// </summary>
        // *** Start programmer edit section *** (DetailUpdateObjectTest.Master CustomAttributes)

        // *** End programmer edit section *** (DetailUpdateObjectTest.Master CustomAttributes)
        [PropertyStorage(new string[] {
                "Master"})]
        public virtual NewPlatform.OrmTestsObjects.MasterUpdateObjectTest Master
        {
            get
            {
                // *** Start programmer edit section *** (DetailUpdateObjectTest.Master Get start)

                // *** End programmer edit section *** (DetailUpdateObjectTest.Master Get start)
                NewPlatform.OrmTestsObjects.MasterUpdateObjectTest result = this.fMaster;
                // *** Start programmer edit section *** (DetailUpdateObjectTest.Master Get end)

                // *** End programmer edit section *** (DetailUpdateObjectTest.Master Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailUpdateObjectTest.Master Set start)

                // *** End programmer edit section *** (DetailUpdateObjectTest.Master Set start)
                this.fMaster = value;
                // *** Start programmer edit section *** (DetailUpdateObjectTest.Master Set end)

                // *** End programmer edit section *** (DetailUpdateObjectTest.Master Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.OrmTestsObjects.AggregatorUpdateObjectTest.
        /// </summary>
        // *** Start programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest CustomAttributes)

        // *** End programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "AggregatorUpdateObjectTest"})]
        public virtual NewPlatform.OrmTestsObjects.AggregatorUpdateObjectTest AggregatorUpdateObjectTest
        {
            get
            {
                // *** Start programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Get start)

                // *** End programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Get start)
                NewPlatform.OrmTestsObjects.AggregatorUpdateObjectTest result = this.fAggregatorUpdateObjectTest;
                // *** Start programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Get end)

                // *** End programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Set start)

                // *** End programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Set start)
                this.fAggregatorUpdateObjectTest = value;
                // *** Start programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Set end)

                // *** End programmer edit section *** (DetailUpdateObjectTest.AggregatorUpdateObjectTest Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DetailUpdateObjectTestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DetailUpdateObjectTestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DetailUpdateObjectTestE", typeof(NewPlatform.OrmTestsObjects.DetailUpdateObjectTest));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of DetailUpdateObjectTest.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDetailUpdateObjectTest CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDetailUpdateObjectTest CustomAttributes)
    public class DetailArrayOfDetailUpdateObjectTest : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.OrmTestsObjects.DetailArrayOfDetailUpdateObjectTest members)

        // *** End programmer edit section *** (NewPlatform.OrmTestsObjects.DetailArrayOfDetailUpdateObjectTest members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DetailUpdateObjectTest by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DetailUpdateObjectTest.
        /// </summary>
        public DetailArrayOfDetailUpdateObjectTest(NewPlatform.OrmTestsObjects.AggregatorUpdateObjectTest fAggregatorUpdateObjectTest) : 
                base(typeof(DetailUpdateObjectTest), ((ICSSoft.STORMNET.DataObject)(fAggregatorUpdateObjectTest)))
        {
        }
        
        public NewPlatform.OrmTestsObjects.DetailUpdateObjectTest this[int index]
        {
            get
            {
                return ((NewPlatform.OrmTestsObjects.DetailUpdateObjectTest)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.OrmTestsObjects.DetailUpdateObjectTest dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
