//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.OrmTestsObjects
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// FileForTests.
    /// </summary>
    // *** Start programmer edit section *** (FileForTests CustomAttributes)

    // *** End programmer edit section *** (FileForTests CustomAttributes)
    [ICSSoft.STORMNET.StoreInstancesInType(typeof(ICSSoft.STORMNET.Business.SQLDataService), typeof(string))]
    [ICSSoft.STORMNET.StoreInstancesInType(typeof(ICSSoft.STORMNET.Business.PostgresDataService), typeof(string))]
    public class FileForTests : INotifyUpdateProperty, IComparableType
    {
        
        // *** Start programmer edit section *** (FileForTests CustomMembers)

        // *** End programmer edit section *** (FileForTests CustomMembers)

    }
}
