//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.OrmTestsObjects
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Homer.
    /// </summary>
    // *** Start programmer edit section *** (Homer CustomAttributes)

    // *** End programmer edit section *** (Homer CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Homer : ICSSoft.STORMNET.DataObject, INotifyUpdateObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Homer CustomMembers)

        // *** End programmer edit section *** (Homer CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Homer.Name CustomAttributes)

        // *** End programmer edit section *** (Homer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Homer.Name Get start)

                // *** End programmer edit section *** (Homer.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Homer.Name Get end)

                // *** End programmer edit section *** (Homer.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Homer.Name Set start)

                // *** End programmer edit section *** (Homer.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Homer.Name Set end)

                // *** End programmer edit section *** (Homer.Name Set end)
            }
        }
    }
}
