//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.OrmTestsObjects
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NotifyUpdateObjectsGeneratedMock.
    /// </summary>
    // *** Start programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomAttributes)

    // *** End programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomAttributes)
    public class NotifyUpdateObjectsGeneratedMock : INotifyUpdateObjects
    {
        
        // *** Start programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomMembers)

        // *** End programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomMembers)

    }
}
