//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.OrmTestsObjects
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// НаследникМ1.
    /// </summary>
    // *** Start programmer edit section *** (НаследникМ1 CustomAttributes)

    // *** End programmer edit section *** (НаследникМ1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class НаследникМ1 : NewPlatform.OrmTestsObjects.МастерМ
    {
        
        // *** Start programmer edit section *** (НаследникМ1 CustomMembers)

        // *** End programmer edit section *** (НаследникМ1 CustomMembers)

    }
}
